
window.__pageEnterTime__ = Date.now();

putCssToStyle([".index__notice-content___14yYv{display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-ms-flex-align:center;align-items:center;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between}.index__detail-btn___2rR1b{-webkit-flex:0 0 auto;-ms-flex:0 0 auto;flex:0 0 auto;margin-left:16px;color:var(--text-link-normal);font-size:14px;cursor:pointer}.index__detail-btn___2rR1b:hover{color:var(--text-link-hover)}.index__detail-btn___2rR1b:active{color:var(--text-link-pressed)}.index__page-wrapper___3fpEK{display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;height:100%}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB{overflow:hidden;max-width:700px;width:100%;margin:0 auto;-webkit-flex:1;-ms-flex:1;flex:1}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6{width:100%;height:100%}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6 .index__item___3OQoM{-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;-webkit-box-sizing:border-box;box-sizing:border-box;height:61px;padding:0 20px;background:var(--bg-body)}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6 .index__item___3OQoM:hover{background:var(--bg-filler)}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6 .index__item___3OQoM .index__avatar___2IJe9{margin-right:12px}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6 .index__item___3OQoM .index__content___1a-ex{-webkit-flex:1;-ms-flex:1;flex:1}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6 .index__item___3OQoM,.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6 .index__item___3OQoM .index__content___1a-ex .index__top-line___30zfl{display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-ms-flex-align:center;align-items:center}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6 .index__item___3OQoM .index__content___1a-ex .index__top-line___30zfl .index__title___1N1zI{-webkit-flex:1;-ms-flex:1;flex:1;overflow:hidden;white-space:nowrap;-o-text-overflow:ellipsis;text-overflow:ellipsis;font-size:14px;color:var(--text-title)}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6 .index__item___3OQoM .index__content___1a-ex .index__bottom-line___N5vZt{overflow:hidden;white-space:nowrap;-o-text-overflow:ellipsis;text-overflow:ellipsis;font-size:12px;color:var(--text-placeholder)}.index__avatar___2IJe9{width:40px;height:40px;margin-right:8px}.index__page-wrapper___3fpEK .index__list-wrapper___T-leB .index__list___VYuq6 .index__item___3OQoM .index__content___1a-ex .index__top-line___30zfl .index__time___11AWG,.index__time___11AWG{font-size:12px;color:var(--text-placeholder)}"]);

var generateFunc = window.app['pages/official-demotion/pc/index'];

location.hash = "pages/official-demotion/pc/index";

document.dispatchEvent(new CustomEvent('generateFuncReady', {
    detail: { generateFunc: generateFunc },
}));

