;globPageRegistPath = 'custom-wrapper';require("custom-wrapper.js");
;globPageRegistPath = '@native-mobile-components/button/index';require("@native-mobile-components/button/index.js");
;globPageRegistPath = '@native-mobile-components/icon/index';require("@native-mobile-components/icon/index.js");
;globPageRegistPath = '@native-pc-components/dialog/index';require("@native-pc-components/dialog/index.js");
;globPageRegistPath = '@native-pc-components/modal/index';require("@native-pc-components/modal/index.js");
;globPageRegistPath = '@native-pc-components/overlay/index';require("@native-pc-components/overlay/index.js");
;globPageRegistPath = '@native-pc-components/button/index';require("@native-pc-components/button/index.js");
;globPageRegistPath = '@native-pc-components/icon/index';require("@native-pc-components/icon/index.js");
;globPageRegistPath = '@native-pc-components/editor/index';require("@native-pc-components/editor/index.js");
;globPageRegistPath = '@native-mobile-components/fab/index';require("@native-mobile-components/fab/index.js");
;globPageRegistPath = '@native-pc-components/tag/index';require("@native-pc-components/tag/index.js");
;globPageRegistPath = '@native-pc-components/view/index';require("@native-pc-components/view/index.js");
;globPageRegistPath = 'pages/article-detail/pc/index';globPageRegistering = true;;require("pages/article-detail/pc/index.js");