
window.__pageEnterTime__ = Date.now();

putCssToStyle([".index__debug-env___38XGk .index__inspect___J8aAy{padding:20px}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-host___3qyAu{padding-top:40px;-webkit-align-items:center;-ms-flex-align:center;align-items:center;font-size:20px;-webkit-justify-content:space-around;-ms-flex-pack:distribute;justify-content:space-around}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-host___3qyAu .index__radio___1Yw4R::before{position:absolute;bottom:0;left:0;right:0;margin:auto;content:'';width:100%;height:100%}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-header___3CKDd{font-size:12px;padding-top:40px;-webkit-align-items:center;-ms-flex-align:center;align-items:center;text-align:center}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-header___3CKDd .index__header-arg___3NNIa{display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-ms-flex-align:center;align-items:center;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;margin-bottom:20px}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-header___3CKDd .index__header-arg___3NNIa:last-child{margin-bottom:0}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-header___3CKDd .index__header-arg___3NNIa .index__input-left___1YYCJ{border-radius:8px 0 0 8px;background-color:var(--bg-body);color:var(--text-title);width:45%;text-align:center;border-right-width:0}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-header___3CKDd .index__header-arg___3NNIa .index__input-left___1YYCJ.index__showborder___v_OLj,.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-header___3CKDd .index__header-arg___3NNIa .index__input-left___1YYCJ:hover{border-right-width:1px}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-header___3CKDd .index__header-arg___3NNIa .index__input-right___21zcI{border-radius:0 8px 8px 0;background-color:var(--bg-body);color:var(--text-title);width:45%;text-align:center;border-left-width:0}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-header___3CKDd .index__header-arg___3NNIa .index__input-right___21zcI.index__showborder___v_OLj,.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-header___3CKDd .index__header-arg___3NNIa .index__input-right___21zcI:hover{border-left-width:1px}.index__debug-env___38XGk .index__inspect___J8aAy .index__inspect-footer___2eubY{margin-top:40px;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-ms-flex-align:center;align-items:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center}"]);

var generateFunc = window.app['pages/inspect-env/pc/index'];

location.hash = "pages/inspect-env/pc/index";

document.dispatchEvent(new CustomEvent('generateFuncReady', {
    detail: { generateFunc: generateFunc },
}));

